// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYjID8_5ftuoKNQ6Zn-PrBcmjKlIf24wk',
    appId: '1:143325030784:web:e3a68683a330dd7992f965',
    messagingSenderId: '143325030784',
    projectId: 'campus-link-6f11f',
    authDomain: 'campus-link-6f11f.firebaseapp.com',
    storageBucket: 'campus-link-6f11f.appspot.com',
    measurementId: 'G-VVP087Q6B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPxNqLpx7r2D8i4SMtNBPeyfyNakzpRYo',
    appId: '1:143325030784:android:da0dcef34640f52092f965',
    messagingSenderId: '143325030784',
    projectId: 'campus-link-6f11f',
    storageBucket: 'campus-link-6f11f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeXmh_MuZ5rYL9Puo60_1e4s-8DvuGnNU',
    appId: '1:143325030784:ios:a2459120190aab3192f965',
    messagingSenderId: '143325030784',
    projectId: 'campus-link-6f11f',
    storageBucket: 'campus-link-6f11f.appspot.com',
    iosClientId: '143325030784-n8k68olpkrlaatkd26f9r38tg1q6dqi6.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusLinkTeachers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeXmh_MuZ5rYL9Puo60_1e4s-8DvuGnNU',
    appId: '1:143325030784:ios:a2459120190aab3192f965',
    messagingSenderId: '143325030784',
    projectId: 'campus-link-6f11f',
    storageBucket: 'campus-link-6f11f.appspot.com',
    iosClientId: '143325030784-n8k68olpkrlaatkd26f9r38tg1q6dqi6.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusLinkTeachers',
  );
}
